POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Password!"
}

###

GET http://localhost:3001/verify
Content-Type: application/json
Authorization: bearer <token>

{
}