POST http://localhost:3001/users/save
Content-Type: application/json

{
  "username": "testuser",
  "password": "£MyTet132!!!",
  "name": "test user",
  "email": "example@mailinator.com"
}

###

PUT http://localhost:3001/users/save
Content-Type: application/json
Authorization: bearer <token>

{
  "username": "testuser",
  "password": "£MyTet132!!!",
  "name": "test user",
  "email": "example@mailinator.com",
  "stealth": false
}

### 

POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "£MyTet132!!!"
}

###

GET http://localhost:3001/users/me
Content-Type: application/json
Authorization: bearer <token>



### 

PATCH http://localhost:3001/users/password
Content-Type: application/json
Authorization: bearer <token>

{
  "password": "Password!",
  "newPassword": "£MyTet132!!!"
}